import {
  siAndroid,
  siApachemaven,
  siC,
  siDocker,
  siDotnet,
  siExpress,
  siFlyway,
  siGit,
  siGithub,
  siGithubactions,
  siGnubash,
  siGo,
  siGradle,
  siHibernate,
  siJavascript,
  siJest,
  siJunit5,
  siKotlin,
  siKubernetes,
  siMongodb,
  siMysql,
  siNuxt,
  siOpenjdk,
  siPostgresql,
  siPython,
  siQuarkus,
  siReact,
  siSelenium,
  siSpigotmc,
  siSpringboot,
  siSpringsecurity,
  siSqlite,
  siSwagger,
  siTailwindcss,
  siTypescript,
  siVite,
  siVuedotjs,
} from 'simple-icons'

/**
 * Monochrome logos for skills.yml entries. Brand logos come from Simple Icons (Font Awesome has
 * no Kotlin, TypeScript, Nuxt, ...); the few Simple Icons lacks fall back to Font Awesome.
 */
export type SkillIcon = { path: string } | { fa: [string, string] }

const si = (i: { path: string }): SkillIcon => ({ path: i.path })

export const skillIcons: Record<string, SkillIcon> = {
  'Kotlin': si(siKotlin),
  'Java': si(siOpenjdk),
  'JavaScript': si(siJavascript),
  'TypeScript': si(siTypescript),
  'Go': si(siGo),
  'C': si(siC),
  'C#': { fa: ['fas', 'hashtag'] },
  'Python': si(siPython),
  'Shell': si(siGnubash),
  'Oracle': { fa: ['fas', 'database'] },
  'MySQL': si(siMysql),
  'SQLite': si(siSqlite),
  'MongoDB': si(siMongodb),
  'Postgres': si(siPostgresql),
  'Kotlin Multiplatform': si(siKotlin),
  'Android Jetpack': si(siAndroid),
  'JavaFX': si(siOpenjdk),
  'Vue': si(siVuedotjs),
  'Nuxt': si(siNuxt),
  'Tailwind CSS': si(siTailwindcss),
  'Spring Boot': si(siSpringboot),
  'Spring Security': si(siSpringsecurity),
  'JPA / Hibernate': si(siHibernate),
  'Express': si(siExpress),
  'Fabric': { fa: ['fas', 'cube'] },
  'Spigot': si(siSpigotmc),
  'Quarkus': si(siQuarkus),
  'React': si(siReact),
  'Git': si(siGit),
  'GitHub': si(siGithub),
  'GitHub Actions': si(siGithubactions),
  'Docker': si(siDocker),
  'Kubernetes': si(siKubernetes),
  'Vite': si(siVite),
  'Gradle': si(siGradle),
  'Maven': si(siApachemaven),
  'Flyway': si(siFlyway),
  'Swagger': si(siSwagger),
  'Jest': si(siJest),
  'JUnit': si(siJunit5),
  'xUnit': si(siDotnet),
  'Playwright': { fa: ['fas', 'masks-theater'] },
  'Selenium': si(siSelenium),
}

export const fallbackIcon: SkillIcon = { fa: ['fas', 'code'] }
